# neuter DMIC PCMs so pipewire can probe them without crashing the DSP
pcm.dmic_null {
    type null
}

# override card 0 DMIC devices
pcm.!card0_dmic99 {
    @args [ CARD ]
    @args.CARD { type string }
    type null
}

pcm.!card0_dmic100 {
    @args [ CARD ] 
    @args.CARD { type string }
    type null
}
